import {EXPLAINFIELD} from "@/assets/common/js/global.js";

let json ={
  "title": "",
  "fieldList": [

    {
      "width":"60",
      "key":"id",
      "title":"",
      "type":"selection",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"",
      "controlType":"hidden",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":false,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"tid",
      "title":"",
      "type":"html",
      "length":"45",
      "isRequire":false,
      "regStr":"",
      "message":"",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"userid",
      "title":"",
      "type":"html",
      "length":"45",
      "isRequire":false,
      "regStr":"",
      "message":"",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"ordernum",
      "title":"订单编号",
      "type":"html",
      "length":"45",
      "isRequire":false,
      "regStr":"",
      "message":"订单编号",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"createtime",
      "title":"创建时间",
      "type":"html",
      "length":"26",
      "isRequire":false,
      "regStr":"",
      "message":"创建时间",
      "controlType":"datetime",
      "max":"",
      "min":"",
      "format":"yyyy-MM-dd HH:mm:ss",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"date"
    }
    ,{
      "key":"paytime",
      "title":"付款时间",
      "type":"html",
      "length":"26",
      "isRequire":false,
      "regStr":"",
      "message":"付款时间",
      "controlType":"datetime",
      "max":"",
      "min":"",
      "format":"yyyy-MM-dd HH:mm:ss",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"date"
    }
    ,{
      "key":"successtime",
      "title":"完成时间",
      "type":"html",
      "length":"26",
      "isRequire":false,
      "regStr":"",
      "message":"完成时间",
      "controlType":"datetime",
      "max":"",
      "min":"",
      "format":"yyyy-MM-dd HH:mm:ss",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"date"
    }
    ,{
      "key":"sendtime",
      "title":"发货时间",
      "type":"html",
      "length":"26",
      "isRequire":false,
      "regStr":"",
      "message":"发货时间",
      "controlType":"datetime",
      "max":"",
      "min":"",
      "format":"yyyy-MM-dd HH:mm:ss",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"date"
    }
    ,{
      "key":"price",
      "title":"总价",
      "type":"html",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"总价",
      "controlType":"integer",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"paytype",
      "title":"支付方式",
      "type":"html",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"支付方式",
      "controlType":"integer",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"status",
      "title":"状态",
      "type":"html",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"状态",
      "controlType":"integer",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"truepay",
      "title":"实付",
      "type":"html",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"实付",
      "controlType":"integer",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"freight",
      "title":"运费",
      "type":"html",
      "length":"10",
      "isRequire":false,
      "regStr":"",
      "message":"运费",
      "controlType":"integer",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"equals",
      "javaType":"integer"
    }
    ,{
      "key":"city",
      "title":"城市",
      "type":"html",
      "length":"255",
      "isRequire":false,
      "regStr":"",
      "message":"城市",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"address",
      "title":"地址",
      "type":"html",
      "length":"255",
      "isRequire":false,
      "regStr":"",
      "message":"地址",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"phone",
      "title":"手机号",
      "type":"html",
      "length":"15",
      "isRequire":false,
      "regStr":"",
      "message":"手机号",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"name",
      "title":"收货人",
      "type":"html",
      "length":"45",
      "isRequire":false,
      "regStr":"",
      "message":"收货人",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
    ,{
      "key":"postal",
      "title":"邮编",
      "type":"html",
      "length":"45",
      "isRequire":false,
      "regStr":"",
      "message":"邮编",
      "controlType":"input",
      "max":"",
      "min":"",
      "format":"",
      "isShowColumn":true,
      "isWhere":true,
      "javaWhere":"like",
      "javaType":"string"
    }
  ]
};

//==== 解释json数据
const obj = EXPLAINFIELD(json);
//=====  标题
export const TitleJson = obj.title;
//===== 添加字段
export const addFieldDataJson = obj.addFieldData;
//===== 修改字段
export const updateFieldDataJson = obj.updateFieldData;
//=====  表头
export const TableHeaderJson = obj.TableHeader;
//=====  搜索字段
export const searchWhereJson = obj.searchWhere;




